// Mocks generated by Mockito 5.4.4 from annotations
// in nasa_picture_domain/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core_foundation/core_foundation.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nasa_picture_domain/src/entity/nasa_picture.dart' as _i5;
import 'package:nasa_picture_domain/src/repository/nasa_picture_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NasaPictureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNasaPictureRepository extends _i1.Mock
    implements _i2.NasaPictureRepository {
  @override
  _i3.Stream<_i4.Result<_i5.NasaPicture, _i2.NasaPictureGetException>> get(
          DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [date],
        ),
        returnValue: _i3.Stream<
            _i4.Result<_i5.NasaPicture, _i2.NasaPictureGetException>>.empty(),
        returnValueForMissingStub: _i3.Stream<
            _i4.Result<_i5.NasaPicture, _i2.NasaPictureGetException>>.empty(),
      ) as _i3
          .Stream<_i4.Result<_i5.NasaPicture, _i2.NasaPictureGetException>>);

  @override
  _i3.Stream<_i4.Result<List<_i5.NasaPicture>, _i2.NasaPictureGetListException>>
      getList() => (super.noSuchMethod(
            Invocation.method(
              #getList,
              [],
            ),
            returnValue: _i3.Stream<
                _i4.Result<List<_i5.NasaPicture>,
                    _i2.NasaPictureGetListException>>.empty(),
            returnValueForMissingStub: _i3.Stream<
                _i4.Result<List<_i5.NasaPicture>,
                    _i2.NasaPictureGetListException>>.empty(),
          ) as _i3.Stream<
              _i4
              .Result<List<_i5.NasaPicture>, _i2.NasaPictureGetListException>>);
}
