name: core_foundation
description: "Flutter package that provides foundation features"
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  freezed_annotation: ^2.1.0
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  test: ^1.25.5
