name: network_service
description: "Network layer for HTTP requests"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  collection: ^1.18.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
