name: nasa_apod

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  ###############################################
  ##              BUILD COMMANDS               ##
  ###############################################
  pub_get:
    run: |
      fvm flutter clean && \
      fvm flutter pub get
    exec:
      concurrency: 1
    description: Clean Flutter package and install dependencies

  codegen:
    run: fvm flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"
    description: Run code generation using build_runner in a specific package

  ###############################################
  ##              TEST COMMANDS                ##
  ###############################################
  test:
    run: fvm flutter test --no-pub --reporter compact
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
    description: Run `flutter test` for a specific package.

  test:all:
    run: melos run test --no-select
    exec:
      concurrency: 1
    description: Run all Flutter tests in this project.

  ###############################################
  ##               RUN COMMANDS                ##
  ###############################################
  run:app:
    exec: fvm flutter run 'MELOS_ROOT_PATH/apps/nasa_apod_app/lib/main.dart'
    packageFilters:
      scope: "nasa_apod_app"

  run:prod-app:
    exec: fvm flutter run --release 'MELOS_ROOT_PATH/apps/nasa_apod_app/lib/main.dart'
    packageFilters:
      scope: "nasa_apod_app"

  run:profile-app:
    exec: fvm flutter run --profile 'MELOS_ROOT_PATH/apps/nasa_apod_app/lib/main.dart'
    packageFilters:
      scope: "nasa_apod_app"
