name: nasa_apod_app
description: "Nasa APOD main flutter application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  core_architecture:
    path: ../../packages/core_architecture

  nasa_picture:
    path: ../features/nasa_picture

  network_service:
    path: ../../packages/network_service

  storage_service:
    path: ../../packages/storage_service

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  yaml: ^3.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/config/
