name: nasa_picture_data
description: "Data layer for Nasa picture feature"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  core_foundation:
    path: ../../../../packages/core_foundation

  network_service:
    path: ../../../../packages/network_service

  storage_service:
    path: ../../../../packages/storage_service

  nasa_picture_domain:
    path: ../nasa_picture_domain

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
