name: core_architecture
description: "Flutter package that provides architectural layers to features"
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  core_foundation:
    path: ../core_foundation
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  go_router: ^14.1.1
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  collection: ^1.18.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
