name: storage_service
description: "Storage layer for database operations"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  path_provider_platform_interface: ^2.0.0
  plugin_platform_interface: ^2.1.8
